name: guardiao_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4 
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fontes/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fontes/BeVietnamPro-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fontes/Lato-Thin.ttf
          weight: 100
        - asset: assets/fontes/Lato-Light.ttf
          weight: 300
        - asset: assets/fontes/Lato-Regular.ttf
          weight: 400
        - asset: assets/fontes/Lato-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/icones/CustomIcons.ttf
  assets:
    - assets/imagens/
    - assets/fontes/
